language: python
python:
  - "2.7"
  - "3.5"

# commands to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install -r dev-requirements.txt"

# commands to run tests
script:
  - "cd docs"
  - "make html"
  - "cd .."
  - "python test_pyopenstates.py"
  - "python setup.py bdist_wheel"
